print("Hi, what is your name?")
name = input()
print (f"Hi, {name} . How old are you?")
age = input()
print("Please enter your date of birth")
DOB = input()
print("Next, Please enter your address")
address = input()
print("Also, what sports do you play?")
sport = input()
print(f"So, your name is {name.capitalize()} , your is {age} years old, born on {DOB} and you live at {address.upper()}.and you like to play {sport.upper()}")
